version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgres_postgis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sinecta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URI: "postgresql://user:password@db:5432/sinecta"  # Cambia 'db' por el nombre del servicio del contenedor de PostgreSQL
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
